version: '3.6'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - '1883:1883'  # Expose MQTT port
      # - '9001:9001'  # Expose MQTT WebSocket port for MQTT over WebSocket
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf  
      - mosquitto_data:/mosquitto/data:rw
      - mosquitto_log:/mosquitto/log:rw
  
  homeassistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    restart: always
    ports:
      - '8123:8123'
    volumes:
      - /home/mine/Desktop/automated_watering/home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus  # Bind-mount D-Bus socket      
    privileged: true
    devices:
      - /dev:/dev
  
volumes:
  grafana_data: {}
  influxdb_data: {}
  mosquitto_data: {}
  mosquitto_log: {}
  homeassistant_data: {}